name: DepthCommands
main: me.gomeow.depthcommands.DepthCommands
author: gomeow
description: Blocks certain commands below a set height.
version: 1.0
website: www.dev.bukkit.org/server-mods/depthcommands/

permissions:
  depthcommands.*:
    description: Gives depth commands permissions.
    children:
      depthcommands.bypass: true
  depthcommands.bypass:
    description: Allows a player to bypass command blocking.